const githutReponseFace = '''
{
  "total_count": 463351,
  "incomplete_results": false,
  "items": [
    {
      "id": 31792824,
      "node_id": "MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==",
      "name": "flutter",
      "full_name": "flutter/flutter",
      "private": false,
      "owner": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/flutter/flutter",
      "description": "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/flutter",
      "forks_url": "https://api.github.com/repos/flutter/flutter/forks",
      "keys_url": "https://api.github.com/repos/flutter/flutter/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/flutter/flutter/teams",
      "hooks_url": "https://api.github.com/repos/flutter/flutter/hooks",
      "issue_events_url": "https://api.github.com/repos/flutter/flutter/issues/events{/number}",
      "events_url": "https://api.github.com/repos/flutter/flutter/events",
      "assignees_url": "https://api.github.com/repos/flutter/flutter/assignees{/user}",
      "branches_url": "https://api.github.com/repos/flutter/flutter/branches{/branch}",
      "tags_url": "https://api.github.com/repos/flutter/flutter/tags",
      "blobs_url": "https://api.github.com/repos/flutter/flutter/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/flutter/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/flutter/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/flutter/flutter/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/flutter/flutter/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/flutter/flutter/languages",
      "stargazers_url": "https://api.github.com/repos/flutter/flutter/stargazers",
      "contributors_url": "https://api.github.com/repos/flutter/flutter/contributors",
      "subscribers_url": "https://api.github.com/repos/flutter/flutter/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/flutter/subscription",
      "commits_url": "https://api.github.com/repos/flutter/flutter/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/flutter/flutter/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/flutter/flutter/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/flutter/flutter/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/flutter/flutter/contents/{+path}",
      "compare_url": "https://api.github.com/repos/flutter/flutter/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/flutter/flutter/merges",
      "archive_url": "https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/flutter/flutter/downloads",
      "issues_url": "https://api.github.com/repos/flutter/flutter/issues{/number}",
      "pulls_url": "https://api.github.com/repos/flutter/flutter/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/flutter/flutter/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/flutter/flutter/labels{/name}",
      "releases_url": "https://api.github.com/repos/flutter/flutter/releases{/id}",
      "deployments_url": "https://api.github.com/repos/flutter/flutter/deployments",
      "created_at": "2015-03-06T22:54:58Z",
      "updated_at": "2022-12-27T04:27:16Z",
      "pushed_at": "2022-12-27T03:07:00Z",
      "git_url": "git://github.com/flutter/flutter.git",
      "ssh_url": "git@github.com:flutter/flutter.git",
      "clone_url": "https://github.com/flutter/flutter.git",
      "svn_url": "https://github.com/flutter/flutter",
      "homepage": "https://flutter.dev",
      "size": 233373,
      "stargazers_count": 147771,
      "watchers_count": 147771,
      "language": "Dart",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 24090,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 11390,
      "license": {
        "key": "bsd-3-clause",
        "name": "BSD 3-Clause New or Revised License",
        "spdx_id": "BSD-3-Clause",
        "url": "https://api.github.com/licenses/bsd-3-clause",
        "node_id": "MDc6TGljZW5zZTU="
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "android",
        "app-framework",
        "cross-platform",
        "dart",
        "dart-platform",
        "desktop",
        "flutter",
        "flutter-package",
        "fuchsia",
        "ios",
        "linux-desktop",
        "macos",
        "material-design",
        "mobile",
        "mobile-development",
        "skia",
        "web",
        "web-framework",
        "windows"
      ],
      "visibility": "public",
      "forks": 24090,
      "open_issues": 11390,
      "watchers": 147771,
      "default_branch": "master",
      "score": 1.0
    },
    {
      "id": 88650014,
      "node_id": "MDEwOlJlcG9zaXRvcnk4ODY1MDAxNA==",
      "name": "plugins",
      "full_name": "flutter/plugins",
      "private": false,
      "owner": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/flutter/plugins",
      "description": "Plugins for Flutter maintained by the Flutter team",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/plugins",
      "forks_url": "https://api.github.com/repos/flutter/plugins/forks",
      "keys_url": "https://api.github.com/repos/flutter/plugins/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/flutter/plugins/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/flutter/plugins/teams",
      "hooks_url": "https://api.github.com/repos/flutter/plugins/hooks",
      "issue_events_url": "https://api.github.com/repos/flutter/plugins/issues/events{/number}",
      "events_url": "https://api.github.com/repos/flutter/plugins/events",
      "assignees_url": "https://api.github.com/repos/flutter/plugins/assignees{/user}",
      "branches_url": "https://api.github.com/repos/flutter/plugins/branches{/branch}",
      "tags_url": "https://api.github.com/repos/flutter/plugins/tags",
      "blobs_url": "https://api.github.com/repos/flutter/plugins/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/plugins/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/plugins/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/flutter/plugins/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/flutter/plugins/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/flutter/plugins/languages",
      "stargazers_url": "https://api.github.com/repos/flutter/plugins/stargazers",
      "contributors_url": "https://api.github.com/repos/flutter/plugins/contributors",
      "subscribers_url": "https://api.github.com/repos/flutter/plugins/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/plugins/subscription",
      "commits_url": "https://api.github.com/repos/flutter/plugins/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/flutter/plugins/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/flutter/plugins/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/flutter/plugins/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/flutter/plugins/contents/{+path}",
      "compare_url": "https://api.github.com/repos/flutter/plugins/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/flutter/plugins/merges",
      "archive_url": "https://api.github.com/repos/flutter/plugins/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/flutter/plugins/downloads",
      "issues_url": "https://api.github.com/repos/flutter/plugins/issues{/number}",
      "pulls_url": "https://api.github.com/repos/flutter/plugins/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/flutter/plugins/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/plugins/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/flutter/plugins/labels{/name}",
      "releases_url": "https://api.github.com/repos/flutter/plugins/releases{/id}",
      "deployments_url": "https://api.github.com/repos/flutter/plugins/deployments",
      "created_at": "2017-04-18T17:02:37Z",
      "updated_at": "2022-12-27T03:39:07Z",
      "pushed_at": "2022-12-26T16:19:20Z",
      "git_url": "git://github.com/flutter/plugins.git",
      "ssh_url": "git@github.com:flutter/plugins.git",
      "clone_url": "https://github.com/flutter/plugins.git",
      "svn_url": "https://github.com/flutter/plugins",
      "homepage": "https://flutter.dev/",
      "size": 35166,
      "stargazers_count": 16609,
      "watchers_count": 16609,
      "language": "Dart",
      "has_issues": false,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 9762,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 97,
      "license": {
        "key": "bsd-3-clause",
        "name": "BSD 3-Clause New or Revised License",
        "spdx_id": "BSD-3-Clause",
        "url": "https://api.github.com/licenses/bsd-3-clause",
        "node_id": "MDc6TGljZW5zZTU="
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "android",
        "dart",
        "flutter",
        "flutter-plugin",
        "ios",
        "plugin"
      ],
      "visibility": "public",
      "forks": 9762,
      "open_issues": 97,
      "watchers": 16609,
      "default_branch": "main",
      "score": 1.0
    },
    {
      "id": 129388994,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMjkzODg5OTQ=",
      "name": "FlutterExampleApps",
      "full_name": "iampawan/FlutterExampleApps",
      "private": false,
      "owner": {
        "login": "iampawan",
        "id": 12619420,
        "node_id": "MDQ6VXNlcjEyNjE5NDIw",
        "avatar_url": "https://avatars.githubusercontent.com/u/12619420?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/iampawan",
        "html_url": "https://github.com/iampawan",
        "followers_url": "https://api.github.com/users/iampawan/followers",
        "following_url": "https://api.github.com/users/iampawan/following{/other_user}",
        "gists_url": "https://api.github.com/users/iampawan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/iampawan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/iampawan/subscriptions",
        "organizations_url": "https://api.github.com/users/iampawan/orgs",
        "repos_url": "https://api.github.com/users/iampawan/repos",
        "events_url": "https://api.github.com/users/iampawan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/iampawan/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/iampawan/FlutterExampleApps",
      "description": "[Example APPS] Basic Flutter apps, for flutter devs.",
      "fork": false,
      "url": "https://api.github.com/repos/iampawan/FlutterExampleApps",
      "forks_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/forks",
      "keys_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/teams",
      "hooks_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/hooks",
      "issue_events_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/issues/events{/number}",
      "events_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/events",
      "assignees_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/assignees{/user}",
      "branches_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/branches{/branch}",
      "tags_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/tags",
      "blobs_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/languages",
      "stargazers_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/stargazers",
      "contributors_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/contributors",
      "subscribers_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/subscribers",
      "subscription_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/subscription",
      "commits_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/contents/{+path}",
      "compare_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/merges",
      "archive_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/downloads",
      "issues_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/issues{/number}",
      "pulls_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/labels{/name}",
      "releases_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/releases{/id}",
      "deployments_url": "https://api.github.com/repos/iampawan/FlutterExampleApps/deployments",
      "created_at": "2018-04-13T10:47:06Z",
      "updated_at": "2022-12-27T04:31:21Z",
      "pushed_at": "2022-03-25T07:04:01Z",
      "git_url": "git://github.com/iampawan/FlutterExampleApps.git",
      "ssh_url": "git@github.com:iampawan/FlutterExampleApps.git",
      "clone_url": "https://github.com/iampawan/FlutterExampleApps.git",
      "svn_url": "https://github.com/iampawan/FlutterExampleApps",
      "homepage": null,
      "size": 112899,
      "stargazers_count": 17880,
      "watchers_count": 17880,
      "language": "Dart",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 3484,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 27,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "android",
        "apps",
        "cross-platform",
        "dart",
        "dartlang",
        "flutter",
        "flutter-apps",
        "flutter-plugin",
        "ios",
        "material-design"
      ],
      "visibility": "public",
      "forks": 3484,
      "open_issues": 27,
      "watchers": 17880,
      "default_branch": "master",
      "score": 1.0
    },
    {
      "id": 90528830,
      "node_id": "MDEwOlJlcG9zaXRvcnk5MDUyODgzMA==",
      "name": "awesome-flutter",
      "full_name": "Solido/awesome-flutter",
      "private": false,
      "owner": {
        "login": "Solido",
        "id": 1295961,
        "node_id": "MDQ6VXNlcjEyOTU5NjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1295961?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Solido",
        "html_url": "https://github.com/Solido",
        "followers_url": "https://api.github.com/users/Solido/followers",
        "following_url": "https://api.github.com/users/Solido/following{/other_user}",
        "gists_url": "https://api.github.com/users/Solido/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Solido/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Solido/subscriptions",
        "organizations_url": "https://api.github.com/users/Solido/orgs",
        "repos_url": "https://api.github.com/users/Solido/repos",
        "events_url": "https://api.github.com/users/Solido/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Solido/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/Solido/awesome-flutter",
      "description": "An awesome list that curates the best Flutter libraries, tools, tutorials, articles and more.",
      "fork": false,
      "url": "https://api.github.com/repos/Solido/awesome-flutter",
      "forks_url": "https://api.github.com/repos/Solido/awesome-flutter/forks",
      "keys_url": "https://api.github.com/repos/Solido/awesome-flutter/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Solido/awesome-flutter/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Solido/awesome-flutter/teams",
      "hooks_url": "https://api.github.com/repos/Solido/awesome-flutter/hooks",
      "issue_events_url": "https://api.github.com/repos/Solido/awesome-flutter/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Solido/awesome-flutter/events",
      "assignees_url": "https://api.github.com/repos/Solido/awesome-flutter/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Solido/awesome-flutter/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Solido/awesome-flutter/tags",
      "blobs_url": "https://api.github.com/repos/Solido/awesome-flutter/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Solido/awesome-flutter/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Solido/awesome-flutter/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Solido/awesome-flutter/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Solido/awesome-flutter/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Solido/awesome-flutter/languages",
      "stargazers_url": "https://api.github.com/repos/Solido/awesome-flutter/stargazers",
      "contributors_url": "https://api.github.com/repos/Solido/awesome-flutter/contributors",
      "subscribers_url": "https://api.github.com/repos/Solido/awesome-flutter/subscribers",
      "subscription_url": "https://api.github.com/repos/Solido/awesome-flutter/subscription",
      "commits_url": "https://api.github.com/repos/Solido/awesome-flutter/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Solido/awesome-flutter/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Solido/awesome-flutter/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Solido/awesome-flutter/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Solido/awesome-flutter/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Solido/awesome-flutter/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Solido/awesome-flutter/merges",
      "archive_url": "https://api.github.com/repos/Solido/awesome-flutter/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Solido/awesome-flutter/downloads",
      "issues_url": "https://api.github.com/repos/Solido/awesome-flutter/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Solido/awesome-flutter/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Solido/awesome-flutter/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Solido/awesome-flutter/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Solido/awesome-flutter/labels{/name}",
      "releases_url": "https://api.github.com/repos/Solido/awesome-flutter/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Solido/awesome-flutter/deployments",
      "created_at": "2017-05-07T11:45:27Z",
      "updated_at": "2022-12-27T01:57:28Z",
      "pushed_at": "2022-12-25T21:18:06Z",
      "git_url": "git://github.com/Solido/awesome-flutter.git",
      "ssh_url": "git@github.com:Solido/awesome-flutter.git",
      "clone_url": "https://github.com/Solido/awesome-flutter.git",
      "svn_url": "https://github.com/Solido/awesome-flutter",
      "homepage": "",
      "size": 3290,
      "stargazers_count": 44570,
      "watchers_count": 44570,
      "language": "Dart",
      "has_issues": false,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 6195,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 44,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "android",
        "awesome",
        "awesome-list",
        "collections",
        "cross-platform",
        "dartlang",
        "flutter",
        "flutter-apps",
        "flutter-examples",
        "flutter-plugin",
        "flutter-plugins",
        "ios",
        "material-design",
        "mobile",
        "mobile-app",
        "mobile-development",
        "reactive-programming",
        "resources"
      ],
      "visibility": "public",
      "forks": 6195,
      "open_issues": 44,
      "watchers": 44570,
      "default_branch": "master",
      "score": 1.0
    }
  ]
}
''';
